workflows:
  ios-app:
    name: Build and Deploy iOS App
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "om.golstan.arkit.new.Zauber"
    scripts:
      - name: Build .ipa file
        script: |
          xcodebuild -project "Harry Pokker.xcodeproj" \
          -scheme "Harry Pokker" \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $HOME/output/HarryPokker.xcarchive archive
          xcodebuild -exportArchive \
          -archivePath $HOME/output/HarryPokker.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath $HOME/output
    artifacts:
      - $HOME/output/*.ipa
    publishing:
      email:
        recipients:
          - "your-email@example.com"
        notify:
          success: true
          failure: true
