workflows:
  ios-native-release:
    name: "Harry Pokker - TestFlight Upload"
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "Harry Pokker.xcodeproj"
        XCODE_SCHEME: "Harry Pokker"
    scripts:
      - name: Build IPA
        script: |
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/HarryPokker.xcarchive

          xcodebuild -exportArchive \
            -archivePath build/HarryPokker.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa
    artifacts:
      - build/ipa/*.ipa
    publishing:
      app_store_connect:
        # API Key Authentication
        api_key: $APP_STORE_CONNECT_API_KEY  # Environment variable name you set in Codemagic
        key_id: $APPLE_KEY_ID                # Key ID (e.g., 3V3UA4GTAQ)
        issuer_id: $APPLE_ISSUER_ID          # Issuer ID (e.g., 5f7e640c-e4a7-4e32-b364-631385816275)

      # TestFlight configuration (separate from app_store_connect)
      testflight:
        # Beta group must be a LIST (even if only one group)
        beta_groups: 
          - "External Testers" 
