workflows:
  ios-native-release:
    name: "Harry Pokker - TestFlight Upload"
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "Harry Pokker.xcodeproj"
        XCODE_SCHEME: "Harry Pokker"
    scripts:
      - name: Build IPA
        script: |
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/HarryPokker.xcarchive

          xcodebuild -exportArchive \
            -archivePath build/HarryPokker.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa
    artifacts:
      - build/ipa/*.ipa
    publishing:
      app_store_connect:
        # API Key Authentication (all 3 fields are REQUIRED)
        api_key: $APP_STORE_CONNECT_API_KEY  # Environment variable name you set in Codemagic
        key_id: $APPLE_KEY_ID                # Changed from `apple_key_id` to `key_id`
        issuer_id: $APPLE_ISSUER_ID          # Changed from `apple_issuer_id` to `issuer_id`

        # TestFlight configuration (nested under app_store_connect)
        testflight:
          # Beta group must be a LIST (even if only one group)
          beta_groups: 
            - "External Testers" 
