workflows:
  simulator-native-ios:
    name: iOS simulator build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "Harry Pokker.xcodeproj"  # Your project file name here
        XCODE_SCHEME: "Harry Pokker"            # Your Xcode scheme name here
        XCODE_WORKSPACE: "Harry Pokker.xcworkspace" # Ensure workspace is set correctly
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          if [ ! -f "Podfile" ]; then
            echo "No Podfile found, generating one..."
            pod init
            echo "platform :ios, '13.0'" > Podfile
            echo "target 'Harry Pokker' do" >> Podfile
            echo "  use_frameworks!" >> Podfile
            echo "end" >> Podfile
          fi
          pod install
      - name: Build the .app
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
