workflows:
  ios-app:
    name: iOS Build
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Harry Pokker.xcworkspace"
        XCODE_SCHEME: "Harry Pokker"
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Build .ipa file
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE \
          -scheme $XCODE_SCHEME \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $HOME/output/HarryPokker.xcarchive archive \
          -allowProvisioningUpdates
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
          -archivePath $HOME/output/HarryPokker.xcarchive \
          -exportOptionsPlist ./exportOptions.plist \
          -exportPath $HOME/output
    artifacts:
      - $HOME/output/*.ipa
